<?php

class InvitePrestation extends Model {
    //put your code here
        var $table = 'LISTE_INVITES
        LEFT OUTER JOIN INSCRIPTION ON INSCRIPTION.ID = LISTE_INVITES.ID_INSCRIPTION
        LEFT OUTER JOIN ACTIVITE ON ACTIVITE.ID_ACTIVITE = INSCRIPTION.ID_ACTIVITE
        LEFT OUTER JOIN PRESTATION ON PRESTATION.ID_ACTIVITE = ACTIVITE.ID_ACTIVITE
        
        ';

}
