//passage en datetime
ALTER TABLE `inscription` 
CHANGE `DATE_INSCRIPTION` `DATE_INSCRIPTION` DATETIME NOT NULL, 
CHANGE `DATE_PAIEMENT` `DATE_PAIEMENT` DATETIME 
on update CURRENT_TIMESTAMP DEFAULT NULL;

//création de la table prestation
DROP TABLE IF EXISTS `prestation`;
CREATE TABLE IF NOT EXISTS `prestation` (
  `ID_ACTIVITE` int(2) NOT NULL,
  `ID_PRESTATION` int(2) NOT NULL,
  `COUT` int(2) NOT NULL,
  `AGEMIN` int(2) DEFAULT NULL,
  `AGEMAX` int(2) DEFAULT NULL,
  `LIBELLE` varchar(50) NOT NULL,
  `OUVERT_EXT` int(1) NOT NULL,
  PRIMARY KEY (`ID_ACTIVITE`,`ID_PRESTATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;